version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: root
      SPRING_DATA_REDIS_USER: root
      SPRING_DATA_REDIS_USER_PASSWORD: root
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=root
      - REDIS_USER_PASSWORD=root
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
networks:
  monitoring: