server:
  port: 8081

spring:
  application:
    name: InstagramStoriesMetric
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      username: root
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,metrics"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}
hiker:
  api: YOUR_TOKEN
  token: f61x4ard26dhuyb579eqbkdcxj7jlru5
